import turtle
def rectangle1(l, w): #mohammad tamer begin
    turtle.up() #Yazan Tinawi begin
    turtle.right(180)
    turtle.forward(250)
    turtle.right(180)
    turtle.down() #Yazan Tinawi end
    turtle.fillcolor("Chartreuse")
    turtle.begin_fill()
    turtle.forward(l)
    turtle.left(90)
    turtle.forward(w)
    turtle.left(90)
    turtle.forward(l)
    turtle.left(90)
    turtle.forward(w)
    turtle.left(180)
    turtle.forward(80)
    turtle.end_fill()


rectangle1(100, 80)


def triangle1():
    turtle.fillcolor("red")
    turtle.begin_fill()
    turtle.right(45)
    turtle.forward(70)
    turtle.right(90)
    turtle.forward(70)
    turtle.right(45)
    turtle.end_fill()


triangle1()

def square1():
    turtle.up()
    turtle.forward(80)
    turtle.right(90)
    turtle.forward(60)
    turtle.right(90)
    turtle.down()
    turtle.fillcolor("wheat")
    turtle.begin_fill()

    turtle.forward(50)
    turtle.right(90)
    turtle.forward(20)
    turtle.right(90)
    turtle.forward(50)
    turtle.left(90)
    turtle.forward(20)
    turtle.left(90)
    turtle.end_fill()
    turtle.up()
    turtle.fillcolor("dim gray")
    turtle.begin_fill()
    turtle.forward(30)
    turtle.left(90)
    turtle.down()
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(15)
    turtle.left(90)
    turtle.end_fill()
    turtle.up()
    turtle.fillcolor("dim gray")
    turtle.begin_fill()
    turtle.left(90)
    turtle.forward(30)
    turtle.down()
    turtle.forward(15)
    turtle.left(90)
    turtle.forward(15)
    turtle.left(90)
    turtle.forward(15)
    turtle.left(90)
    turtle.forward(15)
    turtle.end_fill()
    turtle.right(180)
    turtle.up()
    turtle.fillcolor("dim gray")
    turtle.begin_fill()
    turtle.forward(20)
    turtle.down()
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(15)
    turtle.end_fill()
    turtle.right(90)
    turtle.up()
    turtle.forward(20)
    turtle.fillcolor("dim gray")
    turtle.begin_fill()
    turtle.down()
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(15)
    turtle.end_fill()
    turtle.up()
    turtle.forward(30)
    turtle.right(90)
    turtle.forward(5)
    turtle.down()
    turtle.fillcolor("dim gray")
    turtle.begin_fill()
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(15)
    turtle.right(90)
    turtle.forward(15)
    turtle.end_fill()

square1() #mohammad tamer end
